### ISSUE TITLE
Issues in Mismatched Parenthesis

### ISSUE THREAD

**Issue by unknownpioneer** [jbzdarkid/TFWiki-scripts#52]
![Screenshot_20231001_114810_com.android.chrome.jpg](https://github.com/jbzdarkid/TFWiki-scripts/assets/114795041/28cab070-11de-4c05-84bc-ccedf53dfa9e)

https://wiki.teamfortress.com/wiki/Team_Fortress_Wiki:Reports/Mismatched_parenthesis

As the image above, The DarkidBOT lists the Archimedes/zh-hans for mismatching the symbols while no error has been found.

**Comment by jbzdarkid** [comment]
There was an issue, I fixed it:
https://wiki.teamfortress.com/w/index.php?title=Archimedes/zh-hans&diff=3502643&oldid=3486652

And then in today's update it was removed from the list
https://wiki.teamfortress.com/w/index.php?title=Team_Fortress_Wiki%3AReports%2FMismatched_parenthesis&type=revision&diff=3521662&oldid=3501775
