### ISSUE TITLE
All articles report should exclude /Page.js and /Page.css

### ISSUE THREAD

**Issue by Tarkoviski** [jbzdarkid/TFWiki-scripts#9]
Examples:
* [Main Page/Page.js](https://wiki.teamfortress.com/wiki/Main_Page/Page.js)
* [Main Page/Page.css](https://wiki.teamfortress.com/wiki/Main_Page/Page.css)

**Comment by jbzdarkid** [comment]
~~Thank you -- I think the bug here is that wiki.get_all_articles doesn't have a namespace restriction.~~
Never mind, I'll add an exclusion list.
